version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    container_name: gift-voucher-frontend
    restart: always
    networks:
      - voucher-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3003:3003"
    container_name: gift-voucher-backend
    restart: always
    networks:
      - voucher-network
    environment:
      - PORT=3003
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}

networks:
  voucher-network:
    driver: bridge 