name = "voucher-validation"
main = "src/index.js"
compatibility_date = "2023-05-18"

# Route configuration to intercept requests to the backend
# This allows the worker to act as middleware for the backend API


route = { pattern = "shop-test-api.requestlab.net/validate-voucher", zone_name = "requestlab.net" }

[vars]
FRONTEND_URL = "https://shop-test.whereismypacket.net"
BACKEND_URL = "https://shop-test-api.requestlab.net/validate-voucher"





[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

# Add your development environment variables here
[dev]
port = 8787 